EasyBuy/urls.py
from django.contrib import admin
from django.conf.urls import url
from django.urls import path,include,re_path
from django.views.static import serve
from .settings import MEDIA_ROOT
from user.views import ActiveUserView

import xadmin


urlpatterns = [
    path('car/', include('car.urls')),
    path('xadmin/', xadmin.site.urls),
    path('captcha/', include('captcha.urls')),  # 生成验证码图片功能
    path('user/',include('user.urls',namespace='user')),  # 用户
    re_path('active/(?P<active_code>.*)/',ActiveUserView.as_view(),name='active'),  # 邮箱激活的路由
    path('usercenter/', include('usercenter.urls', namespace='member')),
    path('', include('goods.urls', namespace='goods')),

    url(r'^media/(?P<path>.*)$',  serve, {"document_root": MEDIA_ROOT}),  # 图片路径


]

apps/user/urls.py
from django.urls import path
from user.views import RegisterView,LoginView

app_name = 'user'

urlpatterns = [
    #注册
    path('register/',RegisterView.as_view(),name='register'),
    #登录
    path('login/',LoginView.as_view(),name='login')



]

apps/user/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.utils import timezone

class UserProfile(AbstractUser):
    nickName = models.CharField(max_length=25, null=True, default='易买网用户', verbose_name='昵称')
    sex = models.IntegerField(default=0, verbose_name='性别1为男0为女')
    idcard = models.CharField(max_length=20, default='未设置', verbose_name='身份证')
    email = models.CharField(max_length=30, unique=True, verbose_name='邮箱')
    mobile = models.CharField(max_length=11, unique=True, verbose_name='手机号')
    time = models.DateTimeField(auto_now_add=True, verbose_name='登录时间')
    score = models.IntegerField(default=0, verbose_name='积分')  # 100scroe=1￥
    money = models.FloatField(default=0, verbose_name='余额')
    cost = models.IntegerField(default=0, verbose_name='总消费')
    photo = models.ImageField(upload_to='img/%Y/%m', default='default.jpg', verbose_name='头像')


    class Meta:
        verbose_name = '用户信息'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.username


class EmailVerify(models.Model):
    code = models.CharField(max_length=20,verbose_name='验证码')
    email = models.EmailField(max_length=50,verbose_name='邮箱')
    send_type = models.CharField(default='注册', max_length=30)
    send_time = models.DateTimeField(default=timezone.now)

    class Meta:
        verbose_name = '邮箱验证码'
        verbose_name_plural = verbose_name


class Record(models.Model):
    userId = models.ForeignKey(UserProfile, on_delete=models.CASCADE, verbose_name='用户id')
    money = models.FloatField(verbose_name='余额')
    note = models.CharField(max_length=255, verbose_name='备注')
    pay = models.CharField(max_length=255, verbose_name='支付方式')
    time = models.DateTimeField(auto_now_add=True, verbose_name='创建时间')

    class Meta:
        verbose_name = '充值记录'
        verbose_name_plural = verbose_name

apps/user/forms.py
from django import forms
from captcha.fields import CaptchaField

class RegisterForm(forms.Form):
    ''' 注册验证表单 '''
    username = forms.CharField(required=True)
    password1 = forms.CharField(required=True,min_length=5,error_messages={'invalid':"密码不能少于5位数"})
    password2 = forms.CharField(required=True,min_length=5,error_messages={'invalid':"两次密码不一样"})
    email = forms.EmailField(required=True,error_messages={'invalid':"邮箱格式错误"})
    tel = forms.CharField(required=True,max_length=11,error_messages={'invalid':"手机号码格式错误"})
    #验证码
    captcha = CaptchaField(error_messages={"invalid":"验证码错误"})

apps/user/views.py
from django.shortcuts import render, HttpResponse, redirect, reverse
from django.db.models import Q
from user.models import UserProfile, EmailVerify
from django.views.generic.base import View
from .forms import RegisterForm
from django.contrib.auth.hashers import make_password, check_password
from apps.utils.send_email import send_register_email
from apps.utils.send_email import send_register_email
from datetime import datetime


# 注册
class RegisterView(View):
    def get(self, request):
        if request.method == 'GET':
            register_form = RegisterForm()
            return render(request, 'users/Regist.html', {'register_form': register_form})

    def post(self, request):
        register_form = RegisterForm(request.POST)
        print(register_form.data)
        if register_form.is_valid():
            user_name = request.POST.get('username', None)
            if UserProfile.objects.filter(username=user_name):
                return render(request, 'users/Regist.html', {'register_form': register_form, 'msg': '用户已存在'})

            password1 = request.POST.get('password1', None)
            password2 = request.POST.get('password2', None)
            email = request.POST.get('email', None)
            tel = request.POST.get('tel', None)
            if password1 == password2:
                user_profile = UserProfile()
                # 实例化UserProfile对象
                user_profile.username = user_name
                user_profile.email = email
                user_profile.mobile = int(tel)

                user_profile.is_active = False

                user_profile.password = make_password(password1)
                user_profile.save()
                send_register_email(email)
                return render(request, 'users/Login.html')
            else:
                return render(request, 'users/Regist.html', {'register_form': register_form})
        else:
            return render(request, 'users/Regist.html', {'register_form': register_form})


# 激活邮箱验证码
class ActiveUserView(View):
    def get(self, request, active_code):
        all = EmailVerify.objects.filter(code=active_code)
        if all:
            for i in all:
                email = i.email
                user = UserProfile.objects.get(email=email)

                user.is_active = True
                user.save()

        else:
            return render(request, 'users/active_fail.html')

        return render(request, 'users/Login.html')


# 登录
class LoginView(View):
    def get(self, request):
        return render(request, 'users/Login.html')

    def post(self, request):
        # return HttpResponse("post提交")
        username = request.POST.get("username")
        password = request.POST.get("pwd")
        # 判断数据输入得完整性
        if not all([username, password]):
            return render(request, 'users/Login.html', {'errmsg': '数据不完整'})
        # user = authenticate(username=username, password=password)
        # user = UserProfile.objects.filter(username=username,password=password)

        try:
            user = UserProfile.objects.get(username=username)
            a = check_password(password, user.password)
            if a:
                if user.is_active == 0:
                    return HttpResponse("未激活")
                else:
                    index = redirect(reverse('goods:index'))
                    index.set_cookie("username", username)
                    user.last_login = datetime.now()
                    user.save()
                    return index

            else:
                return render(request, 'users/Login.html', {'errmsg': '密码输入错误'})
        except:
            return render(request, 'users/Login.html', {'errmsg': '用户名不存在'})

templates/users/Login.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
{% load static %}
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<link type="text/css" rel="stylesheet" href="../../static/css/style.css" />
    <!--[if IE 6]>
    <script src="../../static/js/iepng.js" type="text/javascript"></script>
    <script type="text/javascript">
        EvPNG.fix('div, ul, img, li, input, a');
    </script>
    <![endif]-->
    <script type="text/javascript" src="../../static/js/jquery-1.11.1.min_044d0927.js"></script>
	<script type="text/javascript" src="../../static/js/jquery.bxslider_e88acd1b.js"></script>

    <script type="text/javascript" src="../../static/js/jquery-1.8.2.min.js"></script>
    <script type="text/javascript" src="../../static/js/menu.js"></script>

	<script type="text/javascript" src="../../static/js/select.js"></script>

	<script type="text/javascript" src="../../static/js/lrscroll.js"></script>

    <script type="text/javascript" src="../../static/js/iban.js"></script>
    <script type="text/javascript" src="../../static/js/fban.js"></script>
    <script type="text/javascript" src="../../static/js/f_ban.js"></script>
    <script type="text/javascript" src="../../static/js/mban.js"></script>
    <script type="text/javascript" src="../../static/js/bban.js"></script>
    <script type="text/javascript" src="../../static/js/hban.js"></script>
    <script type="text/javascript" src="../../static/js/tban.js"></script>

	<script type="text/javascript" src="../../static/js/lrscroll_1.js"></script>


<title>登录</title>
</head>
<body>
<!--Begin Header Begin-->
<div class="soubg">
	<div class="sou">
        <span class="fr">
        	<span class="fl">你好，请<a href="{% url 'user:login' %}">登录</a>&nbsp; <a href="{% url 'user:register' %}" style="color:#ff4e00;">免费注册</a>&nbsp; </span>
            <span class="fl">|&nbsp;关注我们：</span>
            <span class="s_sh"><a href="#" class="sh1">新浪</a><a href="#" class="sh2">微信</a></span>
            <span class="fr">|&nbsp;<a href="#">手机版&nbsp;<img src="../../static/images/s_tel.png" align="absmiddle" /></a></span>
        </span>
    </div>
</div>
<!--End Header End-->
<!--Begin Login Begin-->
<div class="log_bg">
    <div class="top">
        <div class="logo"><a href="../goods/Index.html"><img src="../../static/images/logo.png" /></a></div>
    </div>
	<div class="login">
    	<div class="log_img"><img src="../../static/images/l_img.png" width="611" height="425" /></div>
		<div class="log_c">
        	<form method="post" >
                {%  csrf_token %}
            <table border="0" style="width:370px; font-size:14px; margin-top:30px;" cellspacing="0" cellpadding="0">
              <tr height="50" valign="top">
              	<td width="55">&nbsp;</td>
                <td>
                	<span class="fl" style="font-size:24px;">登录</span>
                    <span class="fr">还没有商城账号，<a href="{% url 'user:register' %}" style="color:#ff4e00;">立即注册</a></span>
                </td>
              </tr>
              <tr height="70">
                <td>用户名</td>
                <td><input type="text" name="username" value="" class="l_user" /></td>
              </tr>
              <tr height="70">
                <td>密&nbsp; &nbsp; 码</td>
                <td><input type="password" name="pwd" value="" class="l_pwd" /></td>
              </tr>
              <tr>
              	<td>&nbsp;</td>
                <td style="font-size:12px; padding-top:20px;">
                </td>
              </tr>
              <tr height="60">
              	<td>&nbsp;</td>
                <td><input type="submit" value="登录" class="log_btn" /></td>
              </tr>
            </table>
            </form>
            {{ errmsg }}
        </div>
    </div>
</div>
<!--End Login End-->
<!--Begin Footer Begin-->
<div class="btmbg">
    <div class="btm">
        备案/许可证编号：蜀ICP备12009302号-1-www.dingguagua.com   Copyright © 2015-2018 尤洪商城网 All Rights Reserved. 复制必究 , Technical Support: Dgg Group <br />
        <img src="../../static/images/b_1.gif" width="98" height="33" /><img src="../../static/images/b_2.gif" width="98" height="33" /><img src="../../static/images/b_3.gif" width="98" height="33" /><img src="../../static/images/b_4.gif" width="98" height="33" /><img src="../../static/images/b_5.gif" width="98" height="33" /><img src="../../static/images/b_6.gif" width="98" height="33" />
    </div>
</div>
<!--End Footer End -->

</body>


<!--[if IE 6]>
<script src="//letskillie6.googlecode.com/svn/trunk/2/zh_CN.js"></script>
<![endif]-->
</html>

templates/users/Regist.html
{% load static %}

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>

<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<link type="text/css" rel="stylesheet" href="../../static/css/style.css" />
    <!--[if IE 6]>
    <script src="../../static/js/iepng.js" type="text/javascript"></script>
    <script type="text/javascript">
        EvPNG.fix('div, ul, img, li, input, a');
    </script>
    <![endif]-->    
    <script type="text/javascript" src="../../static/js/jquery-1.11.1.min_044d0927.js"></script>
	<script type="text/javascript" src="../../static/js/jquery.bxslider_e88acd1b.js"></script>
    
    <script type="text/javascript" src="../../static/js/jquery-1.8.2.min.js"></script>
    <script type="text/javascript" src="../../static/js/menu.js"></script>
        
	<script type="text/javascript" src="../../static/js/select.js"></script>
    
	<script type="text/javascript" src="../../static/js/lrscroll.js"></script>
    
    <script type="text/javascript" src="../../static/js/iban.js"></script>
    <script type="text/javascript" src="../../static/js/fban.js"></script>
    <script type="text/javascript" src="../../static/js/f_ban.js"></script>
    <script type="text/javascript" src="../../static/js/mban.js"></script>
    <script type="text/javascript" src="../../static/js/bban.js"></script>
    <script type="text/javascript" src="../../static/js/hban.js"></script>
    <script type="text/javascript" src="../../static/js/tban.js"></script>
    
	<script type="text/javascript" src="../../static/js/lrscroll_1.js"></script>
    
    
<title>注册</title>
</head>
<body>  
<!--Begin Header Begin-->
<div class="soubg">
	<div class="sou">
        <span class="fr">
        	<span class="fl">你好，请<a href="{% url 'user:login' %}">登录</a>&nbsp; <a href="{% url 'user:register' %}" style="color:#ff4e00;">免费注册</a>&nbsp; </span>
            <span class="fl">|&nbsp;关注我们：</span>
            <span class="s_sh"><a href="#" class="sh1">新浪</a><a href="#" class="sh2">微信</a></span>
            <span class="fr">|&nbsp;<a href="#">手机版&nbsp;<img src="../../static/images/s_tel.png" align="absmiddle" /></a></span>
        </span>
    </div>
</div>
<!--End Header End--> 
<!--End Header End-->
<!--Begin Login Begin-->
<div class="log_bg">	
    <div class="top">
        <div class="logo"><a href="../goods/Index.html"><img src="../../static/images/logo.png" /></a></div>
    </div>
	<div class="regist">
    	<div class="log_img"><img src="../../static/images/l_img.png" width="611" height="425" /></div>
		<div class="reg_c">
        	<form method="post"  autocomplete="on">

            <table border="0" style="width:420px; font-size:14px; margin-top:20px;" cellspacing="0" cellpadding="0">
              <tr height="50" valign="top">
              	<td width="95">&nbsp;</td>
                <td>
                	<span class="fl" style="font-size:24px;">注册</span>
                    <span class="fr">已有商城账号，<a href="{% url 'user:login' %}" style="color:#ff4e00;">我要登录</a></span>
                </td>
              </tr>
              <tr height="50" class="form-group marb20 {% if register_form.errors.username %}errorput{% endif %}">
{#                  <label align="right"><font color="#ff4e00">*</font>&nbsp; 用户名 </label>#}
                <td align="right"><font color="#ff4e00">*</font>&nbsp;用户名 &nbsp;</td>

                <td><input name="username"  type="text"  class="l_user" placeholder="用户名" required="on" maxlength="10"/></td>
              </tr>

              <tr height="50">
                <td align="right"><font color="#ff4e00">*</font>&nbsp;密码 &nbsp;</td>
                <td><input name='password1'  type="password" value="" class="l_pwd" required="on" placeholder="密码"/></td>
              </tr>
              <tr height="50">
                <td align="right"><font color="#ff4e00">*</font>&nbsp;确认密码 &nbsp;</td>
                <td><input name="password2" type="password" value="" class="l_pwd" required="on"/></td>
              </tr>
              <tr height="50" >
                <td align="right" ><font color="#ff4e00">*</font>&nbsp;邮箱 &nbsp;</td>
                <td >
                    <input name="email" type="email" value="" class="l_email" required="on"/>
                </td>
              </tr>
              <tr height="50">
                <td align="right"><font color="#ff4e00">*</font>&nbsp;手机 &nbsp;</td>
                <td><input name="tel" type="text" value="" class="l_tel" required="on"/></td>
              </tr>
{#              <tr height="50">#}
{#                <td align="right">邀请人会员名 &nbsp;</td>#}
{#                <td><input type="text" value="" class="l_mem" /></td>#}
{#              </tr>#}
{#              <tr height="50">#}
{#                <td align="right">邀请人ID号 &nbsp;</td>#}
{#                <td><input type="text" value="" class="l_num" /></td>#}
{#              </tr>#}
              <tr height="50">
                <td align="right" > <font color="#ff4e00">*</font>&nbsp;验证码 &nbsp;</td>
                <td >
{#                    <input type="text" value="" class="l_ipt" />#}
{#                    <a href="#" style="font-size:12px; font-family:'宋体';">换一张</a>#}
                    {{ register_form.captcha }}
                </td>
              </tr>

              <tr>
              	<td>&nbsp;</td>
                <td style="font-size:12px; padding-top:20px;">
                	<span style="font-family:'宋体';" class="fl">
                    	<label class="r_rad"><input type="checkbox" name="ok"/></label><label class="r_txt">我已阅读并接受《用户协议》</label>
                    </span>
                </td>
              </tr>
              <tr height="60">
              	<td>&nbsp;</td>
                <td><input type="submit" id="btn_submit" value="立即注册" class="log_btn" /></td>
              </tr>
                <tr height="100">
                    {% for key,error in register_form.errors.items %}
                            <td style="color: red">{{ error }}</td>
                            {% endfor %}
                            <td>{{ msg }}</td>
                </tr>
            </table>

            </form>
        </div>
    </div>
</div>
<!--End Login End--> 
<!--Begin Footer Begin-->
<div class="btmbg">
    <div class="btm">
        备案/许可证编号：蜀ICP备12009302号-1-www.dingguagua.com   Copyright © 2015-2018 尤洪商城网 All Rights Reserved. 复制必究 , Technical Support: Dgg Group <br />
        <img src="../../static/images/b_1.gif" width="98" height="33" /><img src="../../static/images/b_2.gif" width="98" height="33" /><img src="../../static/images/b_3.gif" width="98" height="33" /><img src="../../static/images/b_4.gif" width="98" height="33" /><img src="../../static/images/b_5.gif" width="98" height="33" /><img src="../../static/images/b_6.gif" width="98" height="33" />
    </div>    	
</div>
<!--End Footer End -->    

</body>


<script src="//letskillie6.googlecode.com/svn/trunk/2/zh_CN.js"></script>

<script src="https://cdn.bootcdn.net/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script src="https://cdn.bootcdn.net/ajax/libs/twitter-bootstrap/4.5.0/js/bootstrap.min.js"></script>
<script type="text/javascript"></script>

<script>

//验证码动态刷新实现
$('.captcha').click(function () {
    $.getJSON("/captcha/refresh/", function (result) {
        $('.captcha').attr('src', result['image_url']);
        $('#id_captcha_0').val(result['key'])
    });
});

{#//后端返回验证失败后的动作#}
{#if('{{ status }}' == 'error'){#}
{#    alert("验证失败，请重新登录！");#}
{#    window.location.assign("/user/register/")#}

{#$('#btn_submit').click(function () {#}
{#        $.ajax({#}
{#            url: '/register/',#}
{#            type: 'post',#}
{#            data: {#}
{#                'csrfmiddlewaretoken': '{{ csrf_token }}',#}
{#                'username': $('#id_username').val(),#}
{#                'password1': $('#id_password1').val(),#}
{#                'password2': $('#id_password2').val(),#}
{#                'tel': $('#id_tel').val(),#}
{#                'email': $('#id_email').val(),#}
{##}
{#                'captcha_1': $('#id_captcha_1').val(),#}
{#                'captcha_0': $('#id_captcha_0').val(),#}
{#            },#}
{#            success: function (args) {#}
{#                alert(args);#}
{#            }#}
{#        })#}
{#    })#}

</script>
</html>

templates/users/active_fail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <p style="color: red;">链接失效</p>
</body>
</html>